databases:
  - name: postgres
    databaseName: example_timu
    user: oleja
    plan: free

services:
  - type: web
    name: risa
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: example_timu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default